server:
  port: 8003

# mybatis配置
mybatis:
  type-aliases-package: com.ecin520.api.entity
  mapper-locations: classpath:mapper/*.xml



# spring配置druid数据源 redis缓存
spring:
  application:
    name: answer-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/ans?useUnicode=true&characterEncoding=utf-8
    username: root
    password: qwer1234
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

# Eureka配置，服务注册位置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id:
      ans-answer-provider-8003

# info服务信息配置
info:
  app.name: answer module
  designer.name: ecin520
  designer.school: jxnu

